#!/usr/bin/env python
"""Generate paper/macros.tex (headline numbers) and paper/tables.tex (tables)
from docs/data/*.json so the write-up never drifts from the committed traces.
Run: python paper/make_tables.py"""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
DATA = os.path.join(ROOT, "docs", "data")
OUT = os.path.join(ROOT, "paper", "tables.tex")
OUT_MACROS = os.path.join(ROOT, "paper", "macros.tex")
SCEN = ["honest", "coalition_none", "coalition_min4", "coalition_screened"]
LABEL = {"honest": "Honest", "coalition_none": "Coalition, no defenses", "coalition_min4": "Coalition, min-4 rule",
         "coalition_screened": "Coalition, screens on"}


def esc(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


def main():
    T = {n: json.load(open(os.path.join(DATA, f"{n}.json"))) for n in SCEN}
    out = []
    w = out.append

    # ---- macros with headline numbers -------------------------------------------------
    h = T["honest"]
    cfg = h["config"]
    net = cfg["network"]
    w("% auto-generated by paper/make_tables.py; do not edit by hand")
    w(f"\\newcommand{{\\Seed}}{{{cfg['seed']}}}")
    w(f"\\newcommand{{\\Reciprocity}}{{{net['reciprocity']:.3f}}}")
    w(f"\\newcommand{{\\WithinGrade}}{{{net['withinGradeFrac']:.3f}}}")
    w(f"\\newcommand{{\\Hero}}{{{h['hero']}}}")
    w(f"\\newcommand{{\\Coalition}}{{{', '.join(T['coalition_none']['config']['coalition'])}}}")
    w(f"\\newcommand{{\\ExportSeconds}}{{{sum(t['config']['yearSolveSeconds'] for t in T.values()):.0f}}}")
    allst = [r["stats"]["solveTime"] for t in T.values() for r in t["rotations"]]
    w(f"\\newcommand{{\\MaxSolve}}{{{max(allst):.1f}}}")
    w(f"\\newcommand{{\\MeanSolve}}{{{sum(allst)/len(allst):.1f}}}")
    w(f"\\newcommand{{\\CpsatTime}}{{{cfg['solver']['cpsatTime']}}}")
    w(f"\\newcommand{{\\AnnealIters}}{{{cfg['solver']['annealIters']:,}}}".replace(",", r"\,"))
    w(f"\\newcommand{{\\Workers}}{{{cfg['solver']['workers']}}}")
    w(f"\\newcommand{{\\HonestExactlyOne}}{{{h['summary']['pctExactly1Mean']:.2f}}}")
    w(f"\\newcommand{{\\HonestMet}}{{{h['summary']['meanDistinctMetFinal']:.2f}}}")
    w(f"\\newcommand{{\\RandomMet}}{{{h['summary']['meanDistinctMetFinalRandom']:.2f}}}")
    w(f"\\newcommand{{\\RandomGeOne}}{{{h['summary']['pctGe1RandomMean']:.1f}}}")
    m4 = T["coalition_min4"]["summary"]
    w(f"\\newcommand{{\\MinFourAvgCluster}}{{{m4['coalitionAvgCluster']:.2f}}}")
    w(f"\\newcommand{{\\MinFourIntact}}{{{m4['coalitionIntactRotations']}}}")
    w(f"\\newcommand{{\\NoneIntact}}{{{T['coalition_none']['summary']['coalitionIntactRotations']}}}")
    scr = T["coalition_screened"]["config"]["screen"]
    w(f"\\newcommand{{\\ScreenFlagged}}{{{scr['nFlagged']}}}")
    w(f"\\newcommand{{\\ScreenReturned}}{{{scr['nReturned']}}}")
    w(f"\\newcommand{{\\ScreenFlaggedSet}}{{{', '.join(scr['flags'][0]['members']) if scr['flags'] else '--'}}}")
    six = next((c for c in scr["candidates"] if len(c["members"]) == 6), None)
    w(f"\\newcommand{{\\ScreenSplit}}{{{' $\\mid$ '.join(', '.join(p) for p in six['split']) if six and 'split' in six else '--'}}}")
    w(f"\\newcommand{{\\ScreenHonestCandidates}}{{{len(h['config']['screen']['candidates'])}}}")
    with open(OUT_MACROS, "w") as f:
        f.write("\n".join(out) + "\n")
    out.clear()
    w("% auto-generated by paper/make_tables.py; do not edit by hand")

    # ---- summary table ----------------------------------------------------------------
    w(r"\begin{table}[t]\centering\small")
    w(r"\caption{Headline statistics per scenario (seed \Seed, 16 rotations). ``$\ge 1$'' and ``exactly one'' are percentages of submitters; ``met'' is the mean number of distinct schoolmates a student has shared a table with by rotation 16; cluster statistics describe the six coalition members.}")
    w(r"\label{tab:summary}")
    w(r"\begin{tabular}{@{}lrrrrrrr@{}}\toprule")
    w(r"Scenario & $\ge 1$ (min) & \multicolumn{2}{c}{exactly one} & met & met, & intact & avg. \\")
    w(r" & & mean & min & & random & & cluster \\ \midrule")
    for n in SCEN:
        t = T[n]; S = t["summary"]; ex = [r["stats"]["pctExactly1"] for r in t["rotations"]]
        coal = t["config"]["coalitionMode"]
        w(f"{LABEL[n]} & {S['pctGe1Min']:.1f} & {S['pctExactly1Mean']:.2f} & {min(ex):.1f} & {S['meanDistinctMetFinal']:.2f} & {S['meanDistinctMetFinalRandom']:.2f} & "
          + (f"{S['coalitionIntactRotations']}/16 & {S['coalitionAvgCluster']:.2f}" if coal else "-- & --") + r" \\")
    w(r"\bottomrule\end{tabular}\end{table}")
    w("")

    # ---- honest per-rotation table -------------------------------------------------------
    w(r"\begin{table}[t]\centering\small")
    w(r"\caption{Honest scenario, rotation by rotation. ``2+'' counts submitters with two or more listed peers at their table; repeat pairs are pairs seated together who had already shared a table this year (proposed / random); ``phase'' is the pipeline stage whose seating was kept; time is the wall-clock solve time of the rotation.}")
    w(r"\label{tab:honest}")
    w(r"\begin{tabular}{@{}rlrrrrrrlr@{}}\toprule")
    w(r"rot. & state & $\ge 1$ & exactly one & 2+ & met & met, rnd & repeats (prop./rnd) & phase & time (s) \\ \midrule")
    n_sub = sum(1 for l in h["listed"] if l)
    for r in h["rotations"]:
        s = r["stats"]
        two = round(s["pctGe2"] * n_sub / 100)
        w(f"{r['idx']} & {r['state']} & {s['pctGe1']:.0f} & {s['pctExactly1']:.1f} & {two} & {s['meanDistinctMet']:.1f} & {s['meanDistinctMetRandom']:.1f} & {s['repeatPairs']} / {s['repeatPairsRandom']} & {esc(s['acceptedPhase'])} & {s['solveTime']:.1f} \\\\")
    w(r"\bottomrule\end{tabular}\end{table}")
    w("")

    # ---- coalition per-rotation table -----------------------------------------------------
    w(r"\begin{table}[t]\centering\small")
    w(r"\caption{Coalition outcome per rotation under the three defense levels: size of the largest cluster of coalition members at one table, and the mean cluster size experienced by a member ($\sum_c |c|^2 / 6$).}")
    w(r"\label{tab:coalition}")
    w(r"\begin{tabular}{@{}rl rr rr rr@{}}\toprule")
    w(r" & & \multicolumn{2}{c}{no defenses} & \multicolumn{2}{c}{min-4 rule} & \multicolumn{2}{c}{screens on} \\")
    w(r"rot. & state & largest & mean & largest & mean & largest & mean \\ \midrule")
    for i in range(16):
        row = [str(i + 1), T["coalition_none"]["rotations"][i]["state"]]
        for n in ("coalition_none", "coalition_min4", "coalition_screened"):
            c = T[n]["rotations"][i]["coalition"]
            row += [str(c["maxCluster"]), f"{c['avgCluster']:.2f}"]
        w(" & ".join(row) + r" \\")
    w(r"\bottomrule\end{tabular}\end{table}")
    w("")

    # ---- screen candidates (screened scenario) -------------------------------------------
    w(r"\begin{table}[t]\centering\small")
    w(r"\caption{Coercion screen on the coalition's initial submission (screens-on scenario): every candidate set, how it was detected, and the verdict.}")
    w(r"\label{tab:screen}")
    w(r"\begin{tabular}{@{}p{5.2cm}lll@{}}\toprule")
    w(r"candidate set $S$ & source & verdict & closed split found \\ \midrule")
    for c in scr["candidates"]:
        split = " $\\mid$ ".join(", ".join(p) for p in c["split"]) if "split" in c else "none"
        w(f"{', '.join(c['members'])} & {', '.join(c['sources'])} & {'flagged' if c['flagged'] else 'passes'} & {split} \\\\")
    w(r"\bottomrule\end{tabular}\end{table}")
    w("")

    # ---- parameter table ---------------------------------------------------------------------
    wts = cfg["weights"]
    w(r"\begin{table}[t]\centering\small")
    w(r"\caption{Parameters used for the committed traces.}\label{tab:params}")
    w(r"\begin{tabular}{@{}llr@{}}\toprule")
    w(r"group & parameter & value \\ \midrule")
    rows = [
        ("cohort", "students (grade 11 / 12)", f"{cfg['n']} ({cfg['n11']} / {cfg['n12']})"),
        ("cohort", "true friends per student $K$", cfg["K"]),
        ("cohort", "popularity $\\sigma$ (lognormal)", net["popularitySigma"]),
        ("cohort", "within-grade weight", net["withinBias"]),
        ("cohort", "measured reciprocity", f"{net['reciprocity']:.3f}"),
        ("cohort", "measured within-grade fraction", f"{net['withinGradeFrac']:.3f}"),
        ("cohort", "latent groups $\\mu$, $\\omega$", f"{net['mu']}, {net['omega']}"),
        ("tables", "capacities", "17 $\\times$ 7, 23 $\\times$ 6"),
        ("rotations", "count / first state", f"{cfg['rotations']} / {cfg['firstState']}"),
        ("stage 3", "satisfied submitter", wts["anneal"]["satisfied"]),
        ("stage 3", "extra listed peer", wts["anneal"]["extraPeer"]),
        ("stage 3", "repeat: $m_{ab}$, $\\alpha_{ab}$ coefficients", f"{wts['anneal']['repeatM']}, {wts['anneal']['repeatAlpha']}"),
        ("stage 3", "temperature $T_0 \\to T_1$", f"{wts['anneal']['T0']} $\\to$ {wts['anneal']['T1']}"),
        ("stage 3", "iterations", f"{cfg['solver']['annealIters']:,}"),
        ("stage 4", "weight per student with $\\ge 2$ peers", wts["cpsat"]["twoPlus"]),
        ("stage 4", "repeat scale", wts["cpsat"]["repeatScale"]),
        ("stage 4", "deterministic time budget / workers", f"{cfg['solver']['cpsatTime']} / {cfg['solver']['workers']}"),
        ("run", "seed", cfg["seed"]),
    ]
    for g, p, v in rows:
        w(f"{g} & {p} & {v} \\\\")
    w(r"\bottomrule\end{tabular}\end{table}")
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT_MACROS} and {OUT}")


if __name__ == "__main__":
    main()
